name: dts2dart
version: 0.0.1
description: Generates package:js declarations from TypeScript declaration (.d.ts) files
author: Jirka Daněk <dnk@mail.muni.cz>
#homepage: https://www.example.com

environment:
  sdk: '>=1.13.0-dev <2.0.0'

dependencies:
  js: ^0.6.0-beta
  source_gen: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0' # for pub test
  unittest: any # for Intellij test runner
